---
pipeline:
  test:
    image: rust:slim-stretch
    commands:
      - cargo test

  docker build:
    image: plugins/docker
    repo: ncatelli/mud
    auto_tag: true
    secrets: [ docker_username, docker_password ]
    when:
      branches:
        - master
        - release/*
