version: '3'
services:
  ingress:
    image: nginx:1.15.3-alpine
    volumes:
      - ./frontend/public:/www/mud:ro
      - ./frontend/nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    networks:
      - frontend
      - backend
    depends_on:
      - mud 
  mud:
    build: .
    image: ncatelli/mud:latest
    networks:
      - backend
networks:
  frontend:
  backend:
