version: '3'
services:
  ingress:
    image: nginx:1.15.3-alpine
    volumes:
      - ./frontend/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - frontend
      - backend
    depends_on:
      - frontend
  frontend:
    image: node:8.11.4-alpine
    command: 'sh -c "npm install && npm start"'
    working_dir: /app
    volumes:
      - ./frontend/node:/app
    networks:
      - frontend
  mud:
    build: .
    networks:
      - backend
networks:
  frontend:
  backend:
