version: '3'
services:
  ingress:
    image: nginx:1.15.3-alpine
    volumes:
      - ./frontend/conf/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - frontend
      - backend
  mud:
    build: .
    networks:
      - backend
networks:
  frontend:
  backend:
