[package]
name = "mud"
version = "0.1.0"
authors = ["Nate Catelli <ncatelli@packetfire.org>"]

[dependencies]
ws = "0.7.6"
env_logger = "0.5.12"
serde = "1.0.76"
serde_json = "1.0.26"
serde_derive = "1.0.76"
parser = { path = "../parser" }
